<?php
include("php/config.php");
include("php/session.php");
/*
 * Simple Demo of Duo's Web SDK
 *
 * Simple login form with hardcoded username/password
 * protected using Duo
 */
require_once 'php/web.php';

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY', "THISISMYSUPERSECRETCUSTOMERKEYDONOTSHARE");
/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page. For security reasons, these keys are best stored
 * outside of the webroot in a production implementation.
 */
define('IKEY', "DIKBAPC1CBVPMGA9134H");
define('SKEY', "TBqAntFK345x0ZgrCmHSagqWgtv7TPBM3osGByNV");
define('HOST', "api-cf65bdee.duosecurity.com");

/*
 * STEP 3:
 * Once secondary auth has completed you may log in the user
 */
if (isset($_POST['sig_response'])) {
    /*
     * Verify sig response and log in user. Make sure that verifyResponse
     * returns the username we logged in with. You can then set any
     * cookies/session data for that username and complete the login process.
     */
    $resp = Duo\Web::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
    if ($resp === $_SESSION["tmp_useremail"] && $_SESSION["tmp_role"]=='student') {
        $_SESSION["useremail"] = $_SESSION["tmp_useremail"];
        header('Location: home.html');
    }else if ($resp === $_SESSION["tmp_useremail"] && $_SESSION["tmp_role"]=='ta') {
        $_SESSION["useremail"] = $_SESSION["tmp_useremail"];
        header('Location: hometa.html');
    }else if ($resp === $_SESSION["tmp_useremail"] && $_SESSION["tmp_role"]=='instructor') {
        $_SESSION["useremail"] = $_SESSION["tmp_useremail"];
        header('Location: homeinstructor.html');
    }else{
        header('Location: duo.php');
    }
}
/*
 * STEP 2:
 * verify username and password
 * if the user and pass are good, then generate a sig_request and
 * load up the Duo iframe for secondary authentication
 */
else if (isset($_POST['username']) && isset($_POST['password']) && isset($_POST['role'])) {
    
    /*
        * Perform secondary auth, generate sig request, then load up Duo
        * javascript and iframe.
    */
    $username = $_POST['username'];
    $password = $_POST['password'];
    $role = strtolower($_POST['role']);

    $result = pg_query($db, "SELECT * FROM login WHERE username='$username' and password='$password' and role='$role'");
        $rows = pg_num_rows($result);
        if($rows==1 && strcasecmp($role,"student")==0){
            $_SESSION["tmp_useremail"] = $_POST['username'];
            $_SESSION["tmp_role"] = $_POST['role'];
        }else if($rows==1 && strcasecmp($role,"ta")==0){
            $_SESSION["tmp_useremail"] = $_POST['username'];
            $_SESSION["tmp_role"] = $_POST['role'];
        }else if($rows==1 && strcasecmp($role,"instructor")==0){
            $_SESSION["tmp_useremail"] = $_POST['username'];
            $_SESSION["tmp_role"] = $_POST['role'];
        }else{
            echo "incorrect login";
        }     
    $sig_request = Duo\Web::signRequest(IKEY, SKEY, AKEY, $_POST['username']);
    
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Login V4</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->	
        <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/util.css">
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="css/Duo-Frame.css">
    <!--===============================================================================================-->
    </head>
    <body>
        <div class="limiter">
            <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
                    <iframe id="duo_iframe"
                    data-host="<?php echo HOST; ?>"
                    data-sig-request="<?php echo $sig_request; ?>"
                ></iframe>
            </div>
        </div>
        
        
        <script type="text/javascript" src="js/Duo-Web-v2.js"></script>
        
    <!--===============================================================================================-->
        <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/bootstrap/js/popper.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/daterangepicker/moment.min.js"></script>
        <script src="vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
        <script src="js/main.js"></script>
    
    </body>
    </html>
        
 <?php
    
}
else{
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Login V4</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->	
        <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/util.css">
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
    <!--===============================================================================================-->
    </head>
    <body>
        <div class="limiter">
            <div class="container-login100" style="background-image: url(\'images/bg-01.jpg\');">
                <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
                    <span class="login100-form-title p-b-49 title-font-size">
                        Office Hours Scheduler
                    </span>
                    <form class="login100-form validate-form" action="duo.php" method="POST">
                        <span class="login100-form-title p-b-49">
                            Login
                        </span>
    
                        <div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
                            <span class="label-input100">Username</span>
                            <input class="input100" type="text" name="username" placeholder="Type your username" autocomplete="off">
                            <span class="focus-input100" data-symbol="&#xf206;"></span>
                        </div>
    
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
                            <span class="label-input100">Password</span>
                            <input class="input100" type="password" name="password" placeholder="Type your password">
                            <span class="focus-input100" data-symbol="&#xf190;"></span>
                        </div>
    
                        <div class="wrap-input100 validate-input">
                            <span class="label-input100">Role</span>
                            <select class="input100" name="role">
                                <option value="student">Student</option>
                                <option value="ta">Teaching Assistant</option>
                                <option value="instructor">Instructor</option>
                              </select>
                            <span class="focus-input100" data-symbol="&#xf206;"></span>
                        </div>
                        
                        <div class="text-right p-t-8 p-b-31">
                            <a href="#">
                                Forgot password?
                            </a>
                        </div>
                        
                        <div class="container-login100-form-btn">
                            <div class="wrap-login100-form-btn">
                                <div class="login100-form-bgbtn"></div>
                                <button class="login100-form-btn">
                                    Login
                                </button>
                            </div>
                        </div>
    
                    </form>
                </div>
            </div>
        </div>
        
        
    <!--===============================================================================================-->
        <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/bootstrap/js/popper.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/daterangepicker/moment.min.js"></script>
        <script src="vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
        <script src="vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
        <script src="js/main.js"></script>
    
    </body>
    </html>';
} 
// /*
//  * STEP 1: login form
//  * handled exactly as usual
//  */
// else {
//     // Output simple login form
//     echo "<form action='duo.php' method='post'>";
//     echo "Username: <input type='text' name='user' /> <br />";
//     echo "Password: <input type='password' name='pass' /> <br />";
//     echo "<input type='submit' value='Submit' />";
//     echo "</form>";
// }
// echo "</html>";
 ?>
